---
- name: install MinIO client as version pinned .deb
  ansible.builtin.apt:
    deb: "{{ _minio_client_download_base_url }}/mcli_{{ minio_client_release }}_{{ go_arch }}.deb"
  vars:
    _minio_client_download_base_url: "https://dl.min.io/client/mc/release/linux-{{ go_arch }}/archive"

- name: remove /usr/local/bin/mc
  file:
    path: /usr/local/bin/mc
    state: absent
